/controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

/diff_drive_controller:
  ros__parameters:
    left_wheel_names:
      - "left_wheel_joint"
    right_wheel_names:
      - "right_wheel_joint"
    cmd_vel_timeout: 0.5
    wheel_separation: 0.2
    wheel_radius: 0.025
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]
    enable_odom_tf: true
    use_stamped_vel: true
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.5
    linear.x.min_velocity: -0.5
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 0.5
    linear.x.min_acceleration: -0.5
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
