<?xml version="1.0"?>

<robot name="roomba" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="base_radius" value="0.17"/>
    <xacro:property name="base_height" value="0.092"/>
    <xacro:property name="base_mass" value="2.0"/>
    <xacro:property name="wheel_width" value="0.02"/>
    <xacro:property name="wheel_radius" value="0.025"/>
    <xacro:property name="wheel_mass" value="0.3"/>
    <!-- caster + battery -->
    <xacro:property name="caster_mass" value="1.0"/>

    <link name="base_footprint">
    </link>

    <joint name="footprint_to_base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_height/2}"/>
            <geometry>
                <cylinder length="${base_height}" radius="${base_radius}"/>
            </geometry>
            <material name="body_color">
                <color rgba="0.5 0.5 0.5 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 ${base_height/2}"/>
            <geometry>
                <cylinder length="${base_height}" radius="${base_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${base_height/2}"/>
            <mass value="${base_mass}"/>
            <inertia ixx="${base_mass * base_radius * base_radius / 4.0 + base_mass * base_height * base_height / 12.0}"
                     ixy="0.0"
                     ixz="0.0"
                     iyy="${base_mass * base_radius * base_radius / 4.0 + base_mass * base_height * base_height / 12.0}"
                     iyz="0.0"
                     izz="${base_mass * base_radius * base_radius / 2.0}"/>
        </inertial>
    </link>

    <xacro:macro name="add_wheel" params="*origin prefix parent_link">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <xacro:insert_block name="origin"/>
            <axis xyz="0 1 0"/>
            <parent link="${parent_link}"/>
            <child link="${prefix}_wheel_link"/>
            <limit effort="1.0" velocity="${0.5 / wheel_radius}"/>
        </joint>
        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 ${wheel_width/2} 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
                <material name="wheel_color">
                    <color rgba="0.3 0.3 0.3 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 ${wheel_radius/2} 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 ${wheel_width/2} 0"/>
                <mass value="${wheel_mass}"/>
                <inertia ixx="${wheel_mass * wheel_radius * wheel_radius / 4.0 + wheel_mass * wheel_width * wheel_width / 12.0}"
                        ixy="0.0"
                        ixz="0.0"
                        iyy="${wheel_mass * wheel_radius * wheel_radius / 2.0}"
                        iyz="0.0"
                        izz="${wheel_mass * wheel_radius * wheel_radius / 4.0 + wheel_mass * wheel_width * wheel_width / 12.0}"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:add_wheel prefix="left" parent_link="base_link">
        <origin xyz="0 0.1 0" rpy="0 0 0"/>
    </xacro:add_wheel>

    <xacro:add_wheel prefix="right" parent_link="base_link">
        <origin xyz="0 -0.1 0" rpy="0 0 0"/>
    </xacro:add_wheel>

    <joint name="base_to_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_link"/>
        <origin xyz="0.1 0 0"/>
    </joint>

    <link name="caster_link">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
            <material name="caster_color">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="${caster_mass}"/>
            <inertia ixx="${caster_mass * wheel_radius * wheel_radius * 2.0 / 5.0}"
                     ixy="0.0"
                     ixz="0.0"
                     iyy="${caster_mass * wheel_radius * wheel_radius * 2.0 / 5.0}"
                     iyz="0.0"
                     izz="${caster_mass * wheel_radius * wheel_radius * 2.0 / 5.0}"/>
        </inertial>
    </link>


    <!-- laser -->
    <joint name="base_to_laser_link" type="fixed">
        <origin xyz="0 0 0.3"/>
        <parent link="base_link"/>
        <child link="laser_link"/>
    </joint>

    <link name="laser_link">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            <material name="laser_color">
                <color rgba="0.3 0.3 0.3 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0"/>
            <mass value="0.3"/>
            <inertia ixx="1e-6"
                     ixy="0.0"
                     ixz="0.0"
                     iyy="1e-6"
                     iyz="0.0"
                     izz="1e-6"/>
        </inertial>
    </link>

    <xacro:include filename="$(find roomba_description)/urdf/roomba.ros2_control.xacro"/>
    <xacro:roomba_ros2_control name="roomba"/>
    <xacro:include filename="$(find roomba_description)/urdf/roomba.gazebo.xacro"/>
    <xacro:roomba_gazebo/>

</robot>
